#!/usr/bin/bash

Color_Off='\033[0m' 
BRed="\033[1;31m"         # Red
BGreen="\033[1;32m"       # Green
BBlue="\033[1;34m"        # Blue


MSG_FILE=$1
FILE_CONTENT="$(cat $MSG_FILE | wc -l)"
if [[ $FILE_CONTENT != 0 ]]; then
 printf "${BGreen}Good Commit!${Color_Off}"
else
  printf "${BRed}Bad Commit ${BBlue}\n"
  printf "${BRed}Please add proper commit message and try again ${BBlue}\n"
  #printf "commit-msg hook failed (add --no-verify to bypass)\n"
 
exit 1

fi
exit 0
